//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by nsf_setup.rc
//
#define IDD_INFOBOX                     101
#define IDD_DEVICE                      102
#define IDD_BASIC                       103
#define IDD_EASY                        106
#define IDI_NSF                         128
#define IDI_NSFPLUG                     129
#define IDC_INFO                        1000
#define IDR_INFOMENU                    1000
#define IDC_AUTOSTOP                    1004
#define IDD_FDSPANEL                    1006
#define IDD_MEMORY                      1007
#define IDC_STOPSEC                     1008
#define IDR_MEMMENU                     1008
#define IDC_SECSPIN                     1009
#define IDC_DETECTTIME                  1010
#define IDC_PLAYTIME                    1011
#define IDD_AUDIOPANEL                  1011
#define IDC_FADETIME                    1012
#define IDD_APUPANEL                    1012
#define IDC_SECSPIN2                    1013
#define IDD_DMCPANEL                    1014
#define IDC_PLAYFREQ                    1014
#define IDD_MIXER                       1015
#define IDC_LOOPNUM                     1015
#define IDD_MIXERBOX                    1016
#define IDC_SECSPIN3                    1016
#define IDI_MIXER                       1019
#define IDI_MEMORY                      1020
#define IDD_MEMWRITE                    1022
#define IDD_MASK                        1026
#define IDC_QUALITY                     1026
#define IDR_MIXMENU                     1028
#define IDC_LFP                         1030
#define IDC_DESC                        1031
#define IDC_SLIDER                      1035
#define IDC_MUTE                        1036
#define IDC_ENABLE_PNOISE               1042
#define IDC_PHASE_REFRESH               1043
#define IDC_UNMUTE_ON_RESET             1046
#define IDC_UNMUTE_ON_RESET2            1047
#define IDC_ENABLE_4011                 1050
#define IDC_MOD_PHASE_REFRESH           1053
#define IDC_CAR_PHASE_REFRESH           1054
#define IDC_TITLE                       1055
#define IDC_THRESHOLD                   1056
#define IDC_LPF                         1057
#define IDC_AUTODETECT                  1058
#define IDC_LPF2                        1058
#define IDC_VOL                         1058
#define IDC_UPDATE_PLAYLIST             1059
#define IDC_MASTER                      1059
#define IDC_PAN                         1059
#define IDC_USEALT                      1060
#define IDC_INSERT                      1061
#define IDC_FASTSEEK                    1061
#define IDC_ADDRESS                     1062
#define IDB_KEYHEADER                   1062
#define IDC_VALUE                       1063
#define IDC_WLIST                       1064
#define IDC_DELETE                      1065
#define IDC_DELETE2                     1066
#define IDC_SEND                        1067
#define IDC_FREQ_LIMIT                  1074
#define IDC_ENABLE_DCF                  1076
#define IDC_APU_1                       1083
#define IDC_RESET                       1086
#define IDC_MASKINIT                    1087
#define IDC_REVERSE                     1090
#define IDC_DPCM_ATT                    1092
#define IDC_DPCM_FEEDBACK               1093
#define IDC_NOISE_ATT                   1094
#define IDC_DPCM_HPF                    1095
#define IDC_SONG                        1096
#define IDC_DPCM_LPF                    1096
#define IDC_PREV                        1097
#define IDC_TRI_ATT                     1097
#define IDC_TRI_LPF                     1098
#define IDC_ARTIST                      1099
#define IDC_NOISE_LPF                   1099
#define IDC_COPYRIGHT                   1100
#define IDC_NEXT                        1101
#define IDC_MMC5                        1105
#define IDC_FME7                        1106
#define IDC_VRC6                        1107
#define IDC_VRC7                        1108
#define IDC_N106                        1109
#define IDC_SONGSLIDER                  1110
#define IDC_FORMAT                      1111
#define IDC_PAL                         1111
#define IDC_APU_2                       1131
#define IDC_APU_3                       1132
#define IDC_APU_4                       1133
#define IDC_APU_5                       1134
#define IDC_MMC5_1                      1136
#define IDC_MMC5_2                      1137
#define IDC_MMC5_3                      1138
#define IDC_FME7_1                      1141
#define IDC_FME7_2                      1142
#define IDC_FME7_3                      1143
#define IDC_VRC6_1                      1146
#define IDC_VRC6_2                      1147
#define IDC_VRC6_3                      1148
#define IDC_VRC7_1                      1151
#define IDC_VRC7_2                      1152
#define IDC_VRC7_3                      1153
#define IDC_VRC7_4                      1154
#define IDC_VRC7_5                      1155
#define IDC_VRC7_6                      1156
#define IDC_N106_1                      1157
#define IDC_N106_2                      1158
#define IDC_N106_3                      1159
#define IDC_N106_4                      1160
#define IDC_N106_5                      1161
#define IDC_N106_6                      1162
#define IDC_N106_7                      1163
#define IDC_N106_8                      1164
#define IDC_FDS                         1166
#define IDC_TRACKINFO                   2000
#define IDC_FREQ                        2001
#define IDC_DELAY                       2002
#define IDC_FREQ_TEXT                   2003
#define IDC_DELAY_TEXT                  2004
#define IDC_SETUP                       2005
#define IDC_SETUP2                      2006
#define IDD_INFOBOX2                    2007
#define IDC_SPEED                       2007
#define IDC_VSYNC                       2008
#define ID_DELONE                       2009
#define IDC_PREF_PAL                    2009
#define IDC_VSYNC2                      2009
#define ID_DELALL                       2010
#define IDC_GRAPHIC_MODE                2010
#define IDC_STEREO                      2010
#define IDC_FREQ_MODE                   2011
#define IDC_ANTI_NOISE                  2011
#define IDC_STEREO2                     2011
#define IDC_NSFEPLS                     2011
#define IDC_RANDOMIZE_NOISE             2012
#define IDC_LIMIT                       2013
#define IDC_UNMUTE                      2013
#define IDC_TRI_MUTE                    2014
#define IDC_VELOCITY                    2015
#define ID_READTAG                      2018
#define IDC_SAVE                        2021
#define IDC_LOAD                        2023
#define IDC_ADD                         2024
#define IDC_LIST                        2025
#define IDC_EDIT                        2026
#define IDC_HPF                         2027
#define IDC_COMBO1                      2029
#define IDC_COMBO                       2029
#define IDC_REGION                      2029
#define IDC_NONLINEAR_MIXER             2033
#define IDC_NAME                        2034
#define IDC_FDS_LOWPASS                 2035
#define ID_WRITETAG                     2036
#define IDC_4085_RESET                  2036
#define IDC_WRITE_PROTECT               2037
#define IDC_SERIAL                      2037
#define IDD_TRKINFO                     2039
#define IDC_DUTY_SWAP                   2039
#define ID_TRKINFO                      2040
#define IDD_TRKINFO_SETUP               2058
#define IDB_DIGIT                       2062
#define IDB_KEYBOARD                    2063
#define IDD_PLAIN                       2066
#define IDD_KEYDIALOG                   2066
#define IDD_KEYWINDOW                   2067
#define IDB_ASCII                       2068
#define IDD_KEYHEADER                   2068
#define ID_NEWPLS                       2076
#define IDB_MAIN                        2080
#define IDD_NSFPLUG                     2081
#define IDD_PRESET                      2085
#define ID_PRESET                       2086
#define IDD_MMC5PANEL                   2086
#define IDD_PAN                         2087
#define ID_UPALL                        2088
#define IDD_PANBOX                      2088
#define ID_DOWNALL                      2089
#define IDD_N106PANEL                   2089
#define ID_COMMAND_UP                   2090
#define ID_COMMAND_DOWN                 2091
#define IDR_TRKINFOMENU                 2093
#define ID_COPY                         2094
#define IDR_PANMENU                     2094
#define ID_SETTINGS                     2095
#define ID_MIXER                        32771
#define ID_MEMDLG                       32773
#define ID_JAPANESE                     32774
#define ID_FILE_ABOUT                   32774
#define ID_ENGLISH                      32775
#define ID_32775                        32775
#define ID_VIEW_CHANNELMIXER            32776
#define ID_PANBOX                       32777
#define ID_32778                        32778
#define IDM_MONO                        32779
#define ID_RANDOM                       32780
#define ID_MONO                         32781
#define ID_SPREAD                       32782
#define ID_COMMAND_RESETVOLUME          32783
#define ID_RESET                        32784
#define ID_32785                        32785
#define ID_EASY                         32786
#define ID_CONFIG                       32789
#define ID_MIXERBOX                     32791
#define ID_LOAD                         32793
#define ID_SAVE                         32794
#define ID_MENUITEM32795                32795
#define ID_MASKBOX                      32798
#define IDM_UPALL                       32803
#define IDM_DOWNALL                     32804
#define IDM_RESET                       32805
#define IDS_CANCEL                      40000
#define IDS_APPLY                       40001
#define ID_GENPLS                       40008
#define IDS_LOCALTAG                    40009
#define IDS_READONLYTAG                 40010
#define IDS_FOUNDTAG                    40011
#define IDS_RCONV0                      40016
#define IDS_RCONV1                      40017
#define IDS_RCONV2                      40018
#define IDS_RCONV3                      40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2096
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         2040
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
