#pragma once
// generated by nsfplayenums.py
// 2024-04-23 00:56:27

#define NSFP_LIST_COUNT                                     2
#define NSFP_LIST_ENABLE                                    0
#define NSFP_LIST_LOCALE                                    1

#define NSFP_UNIT_COUNT                                     2
#define NSFP_UNIT_APU0                                      0
#define NSFP_UNIT_APU1                                      1

#define NSFP_GROUP_COUNT                                    3
#define NSFP_GROUP_MAIN                                     0
#define NSFP_GROUP_APU0                                     1
#define NSFP_GROUP_APU1                                     2

#define NSFP_CHANNEL_COUNT                                  5
#define NSFP_CHANNEL_APU0_SQU0                              0
#define NSFP_CHANNEL_APU0_SQU1                              1
#define NSFP_CHANNEL_APU1_TRI                               2
#define NSFP_CHANNEL_APU1_NSE                               3
#define NSFP_CHANNEL_APU1_DPCM                              4

#define NSFP_SET_COUNT                                     22
#define NSFP_SET_VOLUME                                     0
#define NSFP_SET_SAMPLERATE                                 1
#define NSFP_SET_STEREO                                     2
#define NSFP_SET_TITLE_FORMAT                               3
#define NSFP_SET_HEX                                        4
#define NSFP_SET_LOCALE                                     5
#define NSFP_SET_APU0_NONLINEAR                             6
#define NSFP_SET_SQU0_ON                                    7
#define NSFP_SET_SQU0_VOL                                   8
#define NSFP_SET_SQU0_PAN                                   9
#define NSFP_SET_SQU1_ON                                   10
#define NSFP_SET_SQU1_VOL                                  11
#define NSFP_SET_SQU1_PAN                                  12
#define NSFP_SET_TRI_ON                                    13
#define NSFP_SET_TRI_VOL                                   14
#define NSFP_SET_TRI_PAN                                   15
#define NSFP_SET_NSE_ON                                    16
#define NSFP_SET_NSE_VOL                                   17
#define NSFP_SET_NSE_PAN                                   18
#define NSFP_SET_DPCM_ON                                   19
#define NSFP_SET_DPCM_VOL                                  20
#define NSFP_SET_DPCM_PAN                                  21
#define NSFP_SETSTR_COUNT                                   1

#define NSFP_PROP_COUNT                                     6
#define NSFP_PROP_SONG_COUNT                                0
#define NSFP_PROP_LONG                                      1
#define NSFP_PROP_TITLE                                     2
#define NSFP_PROP_INFO                                      3
#define NSFP_PROP_BLOB                                      4
#define NSFP_PROP_LIST                                      5

#define NSFP_SONGPROP_COUNT                                 7
#define NSFP_SONGPROP_INT                                   0
#define NSFP_SONGPROP_SONGTEST                              1
#define NSFP_SONGPROP_LONG                                  2
#define NSFP_SONGPROP_TITLE                                 3
#define NSFP_SONGPROP_INFO                                  4
#define NSFP_SONGPROP_BLOB                                  5
#define NSFP_SONGPROP_LIST                                  6

#define NSFP_TEXT_TEXT                                     73
#define NSFP_ERROR_SET_INVALID                             74
#define NSFP_ERROR_SET_TYPE                                75
#define NSFP_ERROR_SETINT_RANGE                            76
#define NSFP_ERROR_INI_NO_EQUALS                           77
#define NSFP_ERROR_INI_BAD_KEY                             78
#define NSFP_ERROR_INI_BAD_INT                             79
#define NSFP_ERROR_INI_BAD_RANGE                           80
#define NSFP_ERROR_INI_BAD_LIST_KEY                        81
#define NSFP_TEXT_COUNT                                    82

#define NSFP_LOCALE_COUNT                                   2
#define NSFP_LOCALE_ENGLISH                                 0
#define NSFP_LOCALE_JAPANESE                                1
// end of file
