#pragma once
// generated by nsfplayenums.py
// 2024-04-21 23:47:22

#define NSFP_LIST_COUNT                                     2
#define NSFP_LIST_ENABLE                                    0
#define NSFP_LIST_LOCALE                                    1

#define NSFP_UNIT_COUNT                                     2
#define NSFP_UNIT_APU0                                      0
#define NSFP_UNIT_APU1                                      1

#define NSFP_GROUP_COUNT                                    3
#define NSFP_GROUP_MAIN                                     0
#define NSFP_GROUP_APU0                                     1
#define NSFP_GROUP_APU1                                     2

#define NSFP_CHANNEL_COUNT                                  5
#define NSFP_CHANNEL_APU0_SQU0                              0
#define NSFP_CHANNEL_APU0_SQU1                              1
#define NSFP_CHANNEL_APU1_TRI                               2
#define NSFP_CHANNEL_APU1_NSE                               3
#define NSFP_CHANNEL_APU1_DPCM                              4

#define NSFP_SET_COUNT                                     20
#define NSFP_SET_VOLUME                                     0
#define NSFP_SET_SAMPLERATE                                 1
#define NSFP_SET_STEREO                                     2
#define NSFP_SET_TITLE_FORMAT                               3
#define NSFP_SET_LOCALE                                     4
#define NSFP_SET_SQU0_ON                                    5
#define NSFP_SET_SQU0_VOL                                   6
#define NSFP_SET_SQU0_PAN                                   7
#define NSFP_SET_SQU1_ON                                    8
#define NSFP_SET_SQU1_VOL                                   9
#define NSFP_SET_SQU1_PAN                                  10
#define NSFP_SET_TRI_ON                                    11
#define NSFP_SET_TRI_VOL                                   12
#define NSFP_SET_TRI_PAN                                   13
#define NSFP_SET_NSE_ON                                    14
#define NSFP_SET_NSE_VOL                                   15
#define NSFP_SET_NSE_PAN                                   16
#define NSFP_SET_DPCM_ON                                   17
#define NSFP_SET_DPCM_VOL                                  18
#define NSFP_SET_DPCM_PAN                                  19
#define NSFP_SETSTR_COUNT                                   1

#define NSFP_PROP_COUNT                                     5
#define NSFP_PROP_SONGCOUNT                                 0
#define NSFP_PROP_LONG                                      1
#define NSFP_PROP_TITLE                                     2
#define NSFP_PROP_INFO                                      3
#define NSFP_PROP_BLOB                                      4

#define NSFP_SONGPROP_COUNT                                 6
#define NSFP_SONGPROP_INT                                   0
#define NSFP_SONGPROP_SONGTEST                              1
#define NSFP_SONGPROP_LONG                                  2
#define NSFP_SONGPROP_TITLE                                 3
#define NSFP_SONGPROP_INFO                                  4
#define NSFP_SONGPROP_BLOB                                  5

#define NSFP_TEXT_COUNT                                     8
#define NSFP_TEXT_INDEX                                    64
#define NSFP_TEXT_TEXT                                      0
#define NSFP_ERROR_SET_INVALID                              1
#define NSFP_ERROR_SET_TYPE                                 2
#define NSFP_ERROR_SETINT_RANGE                             3
#define NSFP_ERROR_INI_NO_EQUALS                            4
#define NSFP_ERROR_INI_BAD_KEY                              5
#define NSFP_ERROR_INI_BAD_INT                              6
#define NSFP_ERROR_INI_BAD_RANGE                            7

#define NSFP_LOCALE_COUNT                                   2
#define NSFP_LOCALE_ENGLISH                                 0
#define NSFP_LOCALE_JAPANESE                                1

// end of file
